"""Governed local research harness.

The kernel owns lifecycle, approvals, budgets, split isolation, event logging,
artifact hashing, and validation. Optimizers may only replace ``HarnessPolicy``.
"""

from .models import (
    ApprovalRecord,
    ArtifactRecord,
    CandidatePoolReference,
    EndpointClass,
    ExecutionIsolationContract,
    GoalSpec,
    GoalState,
    ProtectedSurfaceContract,
    ProviderExecution,
    ReplicationContract,
    RunEvent,
    RunResult,
    RunSpec,
    RunState,
    RuntimeEnvironment,
    StatisticsContract,
    TrackCManifest,
    TrackSManifest,
)
from .benchmark import (
    CandidateExposureComparison,
    ConfirmationClassification,
    FrozenPoolRankingComparison,
    SharedSplitCommitment,
    SelectionDecision,
    SplitFreezeCommitment,
    TrackCRankingDiagnostic,
)
from .policy import CandidateBudget, FusionContract, HarnessPolicy, QueryViewPolicy, RoutePolicy
from .track_s import (
    CandidateAcceptance,
    C1TypedOverlay,
    EngineProvenance,
    MatchedCampaign,
    MechanismMetrics,
    SMarginRule,
    SelectionScores,
    SeedFinalist,
    TrackSTreatment,
    assert_matched_realized_campaigns,
    select_arm_finalist,
)
from .runner import HarnessAdapter, LocalHarness
from .f1_baselines import (
    BaselineReplay,
    FrozenF1RunSpecV1,
    ResourcePreflight,
    replay_fixture_baselines,
    validate_frozen_f1_runspec,
)
from .validation import ValidationError, validate_run_bundle

__all__ = [
    "ApprovalRecord",
    "ArtifactRecord",
    "CandidateBudget",
    "CandidateAcceptance",
    "CandidateExposureComparison",
    "CandidatePoolReference",
    "C1TypedOverlay",
    "ConfirmationClassification",
    "EndpointClass",
    "EngineProvenance",
    "ExecutionIsolationContract",
    "FrozenPoolRankingComparison",
    "FrozenF1RunSpecV1",
    "FusionContract",
    "GoalSpec",
    "GoalState",
    "HarnessAdapter",
    "HarnessPolicy",
    "LocalHarness",
    "MatchedCampaign",
    "MechanismMetrics",
    "ProtectedSurfaceContract",
    "ProviderExecution",
    "QueryViewPolicy",
    "ReplicationContract",
    "ResourcePreflight",
    "RoutePolicy",
    "RunEvent",
    "RunResult",
    "RunSpec",
    "RunState",
    "RuntimeEnvironment",
    "SelectionDecision",
    "SeedFinalist",
    "SelectionScores",
    "SMarginRule",
    "StatisticsContract",
    "SharedSplitCommitment",
    "SplitFreezeCommitment",
    "TrackCManifest",
    "TrackCRankingDiagnostic",
    "TrackSManifest",
    "TrackSTreatment",
    "assert_matched_realized_campaigns",
    "BaselineReplay",
    "ValidationError",
    "validate_run_bundle",
    "select_arm_finalist",
    "replay_fixture_baselines",
    "validate_frozen_f1_runspec",
]
