"""P2 readiness contracts and the fail-closed internal freeze barrier."""

from .contracts import (
    P2BudgetProfile,
    P2ContractError,
    validate_p2_candidate_freeze_proposal,
    validate_p2_preflight_receipt,
    load_p2_request,
    load_profile,
    validate_p2_aggregate_metric,
    validate_p2_artifact,
    validate_p2_package_bundle,
    validate_p2_train_metric,
)
from .state import Candidate, P2RunStateMachine, P2StateError
from .fixture import (
    DEFAULT_RECEIPT_PATH,
    FIXTURE_ID,
    NEGATIVE_CHECK_IDS,
    P2FixtureError,
    fixture_what_if,
    run_fixture_pilot,
    validate_fixture_execution_manifest,
    validate_fixture_receipt,
)
from .preflight import (
    DEFAULT_REQUIRED_FREE_SPACE_BYTES,
    OWNER_APPROVAL_REQUIRED,
    P2_PREFLIGHT_RECEIPT_PATH,
    build_preflight_receipt,
    build_preflight_receipt_v2,
    preflight_what_if,
    run_p2_preflight,
    write_preflight_receipt,
)
from .measured_contracts import (
    BASE_CANDIDATE_IDS,
    BASE_CONTROL_IDS,
    assert_single_axis_pair,
    build_measured_request,
    can_admit_adaptive_batch,
    committed_blob_sha256,
    git_identity,
    load_measured_request,
    load_profile_uri,
    scientific_payload,
    scientific_payload_sha256,
    validate_stop_reason,
    validate_measured_artifact,
    validate_measured_request_payload,
)
from .active_binding import active_p2_source_uris
from .evaluator_compatibility import (
    build_evaluator_compatibility_evidence,
    load_evaluator_compatibility,
)

__all__ = [
    "Candidate",
    "P2BudgetProfile",
    "P2ContractError",
    "validate_p2_candidate_freeze_proposal",
    "validate_p2_preflight_receipt",
    "P2RunStateMachine",
    "P2StateError",
    "P2FixtureError",
    "DEFAULT_RECEIPT_PATH",
    "FIXTURE_ID",
    "NEGATIVE_CHECK_IDS",
    "fixture_what_if",
    "load_p2_request",
    "load_profile",
    "run_fixture_pilot",
    "validate_p2_aggregate_metric",
    "validate_p2_artifact",
    "validate_fixture_execution_manifest",
    "validate_fixture_receipt",
    "validate_p2_package_bundle",
    "validate_p2_train_metric",
    "DEFAULT_REQUIRED_FREE_SPACE_BYTES",
    "OWNER_APPROVAL_REQUIRED",
    "P2_PREFLIGHT_RECEIPT_PATH",
    "build_preflight_receipt",
    "build_preflight_receipt_v2",
    "preflight_what_if",
    "run_p2_preflight",
    "write_preflight_receipt",
    "BASE_CANDIDATE_IDS",
    "BASE_CONTROL_IDS",
    "assert_single_axis_pair",
    "build_measured_request",
    "can_admit_adaptive_batch",
    "committed_blob_sha256",
    "git_identity",
    "load_measured_request",
    "load_profile_uri",
    "scientific_payload",
    "scientific_payload_sha256",
    "validate_stop_reason",
    "validate_measured_artifact",
    "validate_measured_request_payload",
    "active_p2_source_uris",
    "build_evaluator_compatibility_evidence",
    "load_evaluator_compatibility",
]
